//! Both language implementations consume the same wire corpus, never snapshots
//! generated by the implementation under test.
use newim_protocol::{Message, decode, encode};
use serde_json::Value;

fn assert_same_message(first: &Message, second: &Message, name: &str) {
    assert_eq!(first.protocol_version, second.protocol_version, "{name}");
    assert_eq!(first.version, second.version, "{name}");
    assert_eq!(first.client_msg_id, second.client_msg_id, "{name}");
    assert_eq!(first.server_msg_id, second.server_msg_id, "{name}");
    assert_eq!(first.conversation_id, second.conversation_id, "{name}");
    assert_eq!(first.conversation_seq, second.conversation_seq, "{name}");
    assert_eq!(first.sender_id, second.sender_id, "{name}");
    assert_eq!(first.message_type, second.message_type, "{name}");
    assert_eq!(first.server_time, second.server_time, "{name}");
    // RawValue preserves all payload tokens, stronger than semantic equality.
    assert_eq!(first.payload.get(), second.payload.get(), "{name}");
    assert_eq!(first.supported(), second.supported(), "{name}");
}

fn run_group(group: &str) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../fixtures/cases.json");
    let data = std::fs::read(path).expect("shared Go/Rust fixtures must exist");
    let cases: Value = serde_json::from_slice(&data).expect("valid fixture JSON");
    let mut count = 0;
    for case in cases.as_array().expect("fixture array") {
        if case["group"].as_str() != Some(group) {
            continue;
        }
        count += 1;
        let name = case["name"].as_str().expect("case name");
        let bytes = if let Some(wire) = case["wire"].as_str() {
            assert!(case.get("wireHex").is_none(), "ambiguous wire: {name}");
            wire.as_bytes().to_vec()
        } else {
            let hex = case["wireHex"].as_str().expect("wire or wireHex required");
            assert!(hex.is_ascii() && hex.len().is_multiple_of(2), "{name}");
            (0..hex.len())
                .step_by(2)
                .map(|offset| u8::from_str_radix(&hex[offset..offset + 2], 16).expect("hex byte"))
                .collect()
        };
        let expected = case.get("error").expect("explicit error or null required");
        if expected.is_null() {
            let message = decode(&bytes).unwrap_or_else(|error| panic!("{name}: {error}"));
            assert_eq!(
                message.supported(),
                case["supported"].as_bool().expect("supported"),
                "{name}"
            );
            let encoded = encode(&message).unwrap_or_else(|error| panic!("{name} encode: {error}"));
            let again = decode(&encoded).unwrap_or_else(|error| panic!("{name} redecode: {error}"));
            assert_same_message(&message, &again, name);
        } else {
            let error = decode(&bytes).expect_err(name);
            assert_eq!(
                error.code(),
                expected.as_str().expect("error code"),
                "{name}"
            );
        }
    }
    assert!(count > 0, "No shared fixtures executed for {group}");
}

#[test]
fn golden() {
    run_group("golden");
}

#[test]
fn unknown_fields() {
    run_group("unknown_fields");
}

#[test]
fn unknown_type() {
    run_group("unknown_type");
}

#[test]
fn limits() {
    run_group("limits");
}
